name: Python CI pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - "backend/"
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

  steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: |
        flake8 --exclude=venv

    - name: Run tests
      run: |
        pytest

    - name: Run app
      run: |
        uvicorn api.main:app &
        pid=$!
        for i in {1..10}; do
          if ps -p $pid > /dev/null; then
            echo "App is running"
            break
          else
            echo "Waiting for app to start..."
            sleep 1
          fi
        done
        if ! ps -p $pid > /dev/null; thne
          echo "App failed to start"
          exit 1
        fi
        kill $pid
