name: Python CI pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - "backend/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: ${{ secrets.MINIO_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_PASSWORD }}
        ports:
          - "9000:9000"
          - "9001:9001"

      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: "username"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "test_db"
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Wait for MinIO to be ready
        run: |
          for in in {1..10}; do
            nc -zv localhost 9000 && echo "MinIO is ready" && break
            echo "Waiting for MinIO to be ready..."
            sleep 5
          done
          nc -zv localhost 9000 || { echo "MinIO failed to start"; exit 1; }

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run linting
        run: |
          flake8 --config=.flake8

      - name: Run tests with coverage
        env:
          MINIO_SECRET_KEY: ${{ secrets.MINIO_PASSWORD }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_USER }}
          MINIO_URL: localhost:9000
          MINIO_BUCKET_NAME: test-bucket
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: |
          pytest --cov=backend --cov-report=html:test-reports/

      - name: upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/

      - name: Run app
        run: |
          cd backend
          uvicorn api.main:app &
          for i in {1..30}; do
            curl --fail http://localhost:8000/ && break
            echo "Waiting for app to start..."
            sleep 1
          done
          curl --fail http://localhost:8000/ || { echo "App failed to start"; exit 1; }

      - name: Run migrations
        run: |
          alembic revision --autogenerate
          alembic upgrade head
